camunda:
  bpm:
    admin-user:
      id: admin
      password: admin
      firstName: Admin
    filter:
      create: All tasks
    database:
      schema-update: true
      type: postgres
spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/camunda
    username: camunda
    password: camunda
    driver-class-name: org.postgresql.Driver
